Acceptance Test Pipeline Implementation
pingidentity/terraform-provider-pingdirectory pull request #10
Opened 2023-01-31 22:05 UTC by wesleymccollam

Pipeline support for running acceptance tests

2023-01-31 22:13 UTC, henryrecker-pingidentity requested changes

2023-01-31 22:13 UTC, henryrecker-pingidentity commented on .github/workflows/acceptance-tests.yaml
> +      - '**.go'
We could add the Makefile to this in case the test logic changes.

2023-02-01 15:07 UTC, wesleymccollam commented on .github/workflows/acceptance-tests.yaml
> +      - '**.go'
@henryrecker-pingidentity, added in [this commit](https://github.com/pingidentity/terraform-provider-pingdirectory/commit/f8cae8607740b976af1d5546ec934d8b4e59d052).

2023-02-01 15:30 UTC, henryrecker-pingidentity approved these changes

2023-02-01 15:32 UTC, merged