Connection Handler Resource Type
pingidentity/terraform-provider-pingdirectory pull request #13
Opened 2023-02-02 21:07 UTC by wesleymccollam

2023-02-02 21:52 UTC, henryrecker-pingidentity requested changes

2023-02-02 21:52 UTC, henryrecker-pingidentity commented on internal/acctest/resource/config/connectionhandler/connection_handler_test.go
> +		id:                   "test",
When you change the id of a config resource, the provider handles it by basically deleting and recreating the object. Because of that, I think it's better to test with the id not changing, just so we get coverage of actually updating the resource.

2023-02-02 21:52 UTC, henryrecker-pingidentity commented on internal/acctest/resource/config/connectionhandler/connection_handler_test.go
> +	resource.Test(t, resource.TestCase{
We should add a CheckDestroy to the test. See the location test for an example.

2023-02-02 21:52 UTC, henryrecker-pingidentity commented on internal/provider/provider.go
> +		connectionhandler.NewHttpConnectionHandlerResource,
Keep the resources in alphabetical order in this method, so it's easier to look through.

2023-02-03 16:15 UTC, wesleymccollam commented on internal/acctest/resource/config/connectionhandler/connection_handler_test.go
> +	resource.Test(t, resource.TestCase{
Added in [this commit](https://github.com/pingidentity/terraform-provider-pingdirectory/commit/1e19612432c4225bf1a9e3657fe6c92df9971063)

2023-02-03 16:17 UTC, wesleymccollam commented on internal/acctest/resource/config/connectionhandler/connection_handler_test.go
> +		id:                   "test",
id is replaced with the initial value in [this commit](https://github.com/pingidentity/terraform-provider-pingdirectory/commit/1e19612432c4225bf1a9e3657fe6c92df9971063).

2023-02-03 16:24 UTC, henryrecker-pingidentity requested changes

2023-02-03 16:24 UTC, henryrecker-pingidentity commented on internal/acctest/resource/config/connectionhandler/connection_handler_test.go
> +	names := []string{resourceName, updatedResourceName}
You should use the id here, not the resource name. We're calling PingDirectory in this method, and PD knows the connection handler by its id. Resource name is only relevant to Terraform.

You won't need to use a for loop like the location test, since there is only one id used in this test.

2023-02-03 16:58 UTC, wesleymccollam commented on internal/acctest/resource/config/connectionhandler/connection_handler_test.go
> +	names := []string{resourceName, updatedResourceName}
Updated in [this commit](https://github.com/pingidentity/terraform-provider-pingdirectory/commit/e17ccbfe48a2bad0db10073448a53a508b40a210).

2023-02-03 17:02 UTC, henryrecker-pingidentity approved these changes

2023-02-03 17:03 UTC, merged