changelog generation
pingidentity/terraform-provider-pingdirectory pull request #79
Opened 2023-03-03 20:10 UTC by wesleymccollam

2023-03-03 20:41 UTC, henryrecker-pingidentity commented on scripts/issues_in_release.json
> +{
Should we gitignore this file?

2023-03-03 20:42 UTC, henryrecker-pingidentity commented
How do we run the workflow?

2023-03-03 20:43 UTC, henryrecker-pingidentity commented on scripts/issues_in_release.json
> +{
I see the workflow needs it, nevermind.

2023-03-03 20:44 UTC, wesleymccollam commented
We will trigger this workflow manually

2023-03-03 21:26 UTC, henryrecker-pingidentity approved these changes

2023-03-06 17:39 UTC, henryrecker-pingidentity requested changes

2023-03-06 17:39 UTC, henryrecker-pingidentity commented on scripts/generate-changelog.sh
> +rm -rf header.md new_enhancements.md new_resources.md bug_resolutions.md
Just to be safe I'd remove the "-rf" here. I don't think it's really needed for individual files.

2023-03-06 17:40 UTC, PingDavidR commented on scripts/generate-changelog.sh
> +rm -rf header.md new_enhancements.md new_resources.md bug_resolutions.md
if we are sure the files will exist, agreed.  if there is a possibility any might be missing, the "-f" is sufficient to prevent the error message

2023-03-06 17:48 UTC, wesleymccollam commented on scripts/generate-changelog.sh
> +rm -rf header.md new_enhancements.md new_resources.md bug_resolutions.md
latest commit removes this

2023-03-06 17:52 UTC, henryrecker-pingidentity commented on scripts/generate-changelog.sh
> +rm -rf header.md new_enhancements.md new_resources.md bug_resolutions.md
The "-r" is the one we don't want. We don't want to accidentally remove a directory.

2023-03-06 17:54 UTC, wesleymccollam commented on scripts/generate-changelog.sh
> +rm -rf header.md new_enhancements.md new_resources.md bug_resolutions.md
whoops. corrected now.

2023-03-06 17:57 UTC, henryrecker-pingidentity approved these changes

2023-03-06 17:58 UTC, merged