BRASS 639: updating documentation
pingidentity/terraform-provider-pingdirectory pull request #9
Opened 2023-01-31 20:40 UTC by PingDavidR

- added a TODO document
- added file system explanation
- added notes on specifics of the provider
- other edits

2023-01-31 22:24 UTC, henryrecker-pingidentity requested changes

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on contributing/development.md
> +replace github.com/pingidentity/pingdirectory-go-client v0.0.0 with ==> ./pingdirectory-go-client
Remove the "with" here - this line is a code line that is expected in the go.mod file. https://go.dev/ref/mod#go-mod-file-replace

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on contributing/filelayout.md
> +The **utils** package contains functions used across other packages.
This is out of date - there isn't any utils package any more. Things have been split into operations and types packages.

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on contributing/filelayout.md
> +- **resource/ldap/** contains the non-production-ready resource for managing LDAP users
This no longer exists

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on contributing/filelayout.md
> +## Tests
I would label this "Acceptance Tests"

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on contributing/filelayout.md
> +#### Note on conversions.go:
With the MR I put in this morning, there's no longer a need to update this file. All the generated methods for all the enums are in the client, not the provider.

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on TODO.md
> +- [ ] Investigate splitting the utils package out into more granular packages - Ping internal ticket BRASS-630
This is already done

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on README_ProviderNotes.md
> +Other providers have functionality to manage resources in this category. One particular example is in this AWS provider resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/res
I don't think we need to discuss the AWS provider and how it handles things here.

2023-01-31 22:24 UTC, henryrecker-pingidentity commented on README_ProviderNotes.md
> +When running **_dsconfig_** commands, the instance is referred to using the **name** variable.  The convention in a Terraform provider is to use **id** as the naming attribute in most cases.
It'd be good to show an example of location via dsconfig versus location via terraform here to explain what this means

2023-02-01 20:19 UTC, PingDavidR commented on contributing/development.md
> +replace github.com/pingidentity/pingdirectory-go-client v0.0.0 with ==> ./pingdirectory-go-client
heh, not sure how that go there

2023-02-01 20:33 UTC, PingDavidR commented on README_ProviderNotes.md
> +When running **_dsconfig_** commands, the instance is referred to using the **name** variable.  The convention in a Terraform provider is to use **id** as the naming attribute in most cases.
done

2023-02-01 20:40 UTC, henryrecker-pingidentity approved these changes

2023-02-01 20:42 UTC, merged